"""The repository layer for the core data model (spec 6.2).

Small typed functions that insert and read rows of migration
``0005_core_model.sql``. There is no ORM: a row is a frozen dataclass with the
column names of its table, and a query is written as SQL.
"""

from .area import (
    BROKEN_AFTER_FAILURES,
    add_overlap,
    get_body,
    get_jurisdiction,
    get_person,
    get_seat,
    get_source,
    insert_body,
    insert_jurisdiction,
    insert_person,
    insert_seat,
    insert_source,
    overlaps_of,
    record_source_failure,
)
from .evidence import (
    VOTE_SOURCE_KINDS,
    citation_sha256,
    get_citation,
    get_vote,
    insert_record_citation,
    insert_video_citation,
    insert_vote,
)
from .meetings import (
    get_meeting,
    get_record,
    get_record_page,
    get_video,
    insert_meeting,
    insert_record,
    insert_record_page,
    insert_video,
    primary_video,
    record_pages,
)
from .rows import (
    AgendaItem,
    Body,
    Citation,
    Jurisdiction,
    Meeting,
    Person,
    Record,
    RecordPage,
    Seat,
    Segment,
    Source,
    Transcript,
    Video,
    Vote,
)
from .text import (
    ALIGNMENT_METHODS,
    agenda_items,
    get_agenda_item,
    get_segment,
    get_transcript,
    insert_agenda_item,
    insert_segment,
    insert_transcript,
    item_for_segment,
)

__all__ = [
    "ALIGNMENT_METHODS",
    "BROKEN_AFTER_FAILURES",
    "VOTE_SOURCE_KINDS",
    "AgendaItem",
    "Body",
    "Citation",
    "Jurisdiction",
    "Meeting",
    "Person",
    "Record",
    "RecordPage",
    "Seat",
    "Segment",
    "Source",
    "Transcript",
    "Video",
    "Vote",
    "add_overlap",
    "agenda_items",
    "citation_sha256",
    "get_agenda_item",
    "get_body",
    "get_citation",
    "get_jurisdiction",
    "get_meeting",
    "get_person",
    "get_record",
    "get_record_page",
    "get_seat",
    "get_segment",
    "get_source",
    "get_transcript",
    "get_video",
    "get_vote",
    "insert_agenda_item",
    "insert_body",
    "insert_jurisdiction",
    "insert_meeting",
    "insert_person",
    "insert_record",
    "insert_record_citation",
    "insert_record_page",
    "insert_seat",
    "insert_segment",
    "insert_source",
    "insert_transcript",
    "insert_video",
    "insert_video_citation",
    "insert_vote",
    "item_for_segment",
    "overlaps_of",
    "primary_video",
    "record_pages",
    "record_source_failure",
]
