"""The jobs system of spec 16.1: enqueue, claim, heartbeat, resume.

Long work never runs inside an API request (decision 10 rule 1). A route calls
`enqueue` and returns at once with a job id; a `Runner` claims the job later,
runs its handler, and leaves a resumable checkpoint behind.
"""

from .queue import (
    DONE,
    FAILED,
    FINISHED_STATES,
    ORIGIN_MANUAL,
    ORIGIN_SCHEDULED,
    ORIGINS,
    PAUSED,
    QUEUED,
    RUNNING,
    STATES,
    Claim,
    ClaimLost,
    Clock,
    JobContext,
    JobDeferred,
    JobInterrupted,
    JobNotPaused,
    JobPaused,
    claim,
    enqueue,
    finish,
    get,
    heartbeat,
    pause,
    read_checkpoint,
    requeue_paused,
    requeue_stale,
    return_to_queue,
    save_checkpoint,
    short_reason,
    utcnow,
)
from .registry import Handler, Registry, default_registry, register
from .runner import Runner
from .settings import JobsSettings

__all__ = [
    "DONE",
    "FAILED",
    "FINISHED_STATES",
    "ORIGIN_MANUAL",
    "ORIGIN_SCHEDULED",
    "ORIGINS",
    "PAUSED",
    "QUEUED",
    "RUNNING",
    "STATES",
    "Claim",
    "ClaimLost",
    "Clock",
    "Handler",
    "JobContext",
    "JobDeferred",
    "JobInterrupted",
    "JobNotPaused",
    "JobPaused",
    "JobsSettings",
    "Registry",
    "Runner",
    "claim",
    "default_registry",
    "enqueue",
    "finish",
    "get",
    "heartbeat",
    "pause",
    "read_checkpoint",
    "register",
    "requeue_paused",
    "requeue_stale",
    "return_to_queue",
    "save_checkpoint",
    "short_reason",
    "utcnow",
]
